unit UDMConta;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  IBDatabase, Db, IBCustomDataSet, IBQuery, IBUpdateSQL, IBEvents;
type
	
  TDMCONTA = class(TDataModule)
    IBDB: TIBDatabase;
    IBT: TIBTransaction;
    TAlx: TIBQuery;
    DAlx: TDataSource;
    TPlnCta: TIBQuery;
    TCtaP: TIBQuery;
    TParcCP: TIBQuery;
    TCtaR: TIBQuery;
    TParcCR: TIBQuery;
    UPlnCta: TIBUpdateSQL;
    UCtaP: TIBUpdateSQL;
    UParcCP: TIBUpdateSQL;
    UCtaR: TIBUpdateSQL;
    UParcCR: TIBUpdateSQL;
    DPlnCta: TDataSource;
    DCtaP: TDataSource;
    DParcCP: TDataSource;
    DCtaR: TDataSource;
    DParcCR: TDataSource;
    WCtaP: TIBQuery;
    DWCtaP: TDataSource;
    WParP: TIBQuery;
    DWParP: TDataSource;
    WCtaR: TIBQuery;
    DWCtaR: TDataSource;
    WParR: TIBQuery;
    DWParR: TDataSource;
    TRel: TIBQuery;
    DRel: TDataSource;
    WCtaPCOD_CTAPAGAR: TIntegerField;
    WCtaPCOD_FORMPAG: TIntegerField;
    WCtaPCOD_FORNEC: TIntegerField;
    WCtaPCOD_PLNCTA: TIntegerField;
    WCtaPCOBRANCA: TIBStringField;
    WCtaPDTLANC: TDateField;
    WCtaPHISTORICO: TIBStringField;
    WCtaPVALOR: TIBBCDField;
    WCtaPCOD_USUARIO: TIntegerField;
    WCtaPLOGIN: TIBStringField;
    WCtaPCOD_LOJA: TIntegerField;
    WCtaPNUMDOC: TIBStringField;
    TCConta: TIBQuery;
    UCConta: TIBUpdateSQL;
    DCConta: TDataSource;
    TPlnCtaCOD_PLNCTA: TIntegerField;
    TPlnCtaCLASSIFICACAO: TIBStringField;
    TPlnCtaDESCRICAO: TIBStringField;
    TPlnCtaCODIGOGER: TIBStringField;
    TPlnCtaNATUREZA: TIBStringField;
    TPlnCtaTIPO: TIBStringField;
    TPlnCtaCOD_FILIAL: TIntegerField;
    TPlnCtaVLRPREV: TIBBCDField;
    TPlnCtaVLRREAL: TIBBCDField;
    TPlnCtaPERPREV: TIBBCDField;
    TPlnCtaPERREAL: TIBBCDField;
    TPlnCtaCCF: TIBStringField;
    TPlnCtaNIVEL: TIntegerField;
    TPlnCtaORDEM: TSmallintField;
    TAgenda: TIBQuery;
    UAgenda: TIBUpdateSQL;
    DAgenda: TDataSource;
    Tcontato: TIBQuery;
    UContato: TIBUpdateSQL;
    DContato: TDataSource;
    TParcCPCOD_PARCELACP: TIntegerField;
    TParcCPCOD_CTAPAGAR: TIntegerField;
    TParcCPNUMPARC: TIBStringField;
    TParcCPDTVENC: TDateField;
    TParcCPDTDEBITO: TDateField;
    TParcCPCOD_PARANT: TIntegerField;
    TParcCPDESCONTO: TFloatField;
    TParcCPJUROS: TFloatField;
    TParcCPMULTAS: TFloatField;
    TParcCPVALOR: TIBBCDField;
    TParcCPVALORPG: TIBBCDField;
    TParcCPFECH: TIBStringField;
    TParcCPCOBRANCA: TIBStringField;
    TParcCPCOD_COTA: TIntegerField;
    TParcCPHISTORICO: TIBStringField;
    TParcCPDTREF: TDateField;
    TParcCPPREVISAO: TIBStringField;
    TParcCPMARK: TIBStringField;
    TParcCPTIPO: TSmallintField;
    TPlnCtaMARKREL: TIBStringField;
    TCtaPCOD_CTAPAGAR: TIntegerField;
    TCtaPCOD_USUARIO: TIntegerField;
    TCtaPDTLANC: TDateField;
    TCtaPCOBRANCA: TIBStringField;
    TCtaPCOD_FORNEC: TIntegerField;
    TCtaPCOD_PLNCTA: TIntegerField;
    TCtaPHISTORICO: TIBStringField;
    TCtaPTIPOGERADOR: TIBStringField;
    TCtaPCOD_GERADOR: TIntegerField;
    TCtaPVALOR: TIBBCDField;
    TCtaPCOD_COTAMOEDA: TIntegerField;
    TCtaPCOD_FORMPAG: TIntegerField;
    TCtaPNUMDOC: TIBStringField;
    TCContaCOD_PLNCTA: TIntegerField;
    TCContaCOD_PLNCTAREF: TIntegerField;
    TCContaOPER: TIBStringField;
    TAgendaCOD_AGENDA: TIntegerField;
    TAgendaDATAAG: TDateField;
    TAgendaHORAAG: TTimeField;
    TAgendaASSUNTO: TIBStringField;
    TAgendaDTAVISO: TDateField;
    TAgendaHRAVISO: TTimeField;
    TAgendaFINALIZADO: TIBStringField;
    TAgendaCOD_PARCELACR: TIntegerField;
    TcontatoCOD_CONTATO: TIntegerField;
    TcontatoCOD_AGENDA: TIntegerField;
    TcontatoDTCONTATO: TDateField;
    TcontatoHRCONTATO: TTimeField;
    TcontatoCONTATO: TIBStringField;
    TcontatoTEXTO: TMemoField;
    TParcCRCOD_PARCELACR: TIntegerField;
    TParcCRCOD_CTARECEBER: TIntegerField;
    TParcCRNUMPARC: TIBStringField;
    TParcCRDTDEBITO: TDateField;
    TParcCRCOD_PARANT: TIntegerField;
    TParcCRDESCONTO: TFloatField;
    TParcCRJUROS: TFloatField;
    TParcCRMULTA: TFloatField;
    TParcCRVALOR: TIBBCDField;
    TParcCRVALORPG: TIBBCDField;
    TParcCRFECH: TIBStringField;
    TParcCRCOBRANCA: TIBStringField;
    TParcCRDTVENC: TDateField;
    TParcCRCOD_COTA: TIntegerField;
    TParcCRHISTORICO: TIBStringField;
    TParcCRVALEXT: TIBStringField;
    TParcCRVALORSERV: TIBBCDField;
    TParcCRVALORPROD: TIBBCDField;
    TParcCRMARK: TIBStringField;
    TParcCRIMP: TIBStringField;
    TParcCRNUMBOLETO: TIBStringField;
    TParcCRNUMFISC: TIntegerField;
    TParcCRCOD_CTACOR: TIntegerField;
    TParcCRREMESSA: TIBStringField;
    TParcCRDTREF: TDateField;
    TParcCRPERVLRSERV: TIBBCDField;
    TParcCRAPLICJUR: TSmallintField;
    TParcCRNOSSONUMBLT: TIBStringField;
    TParcCRSCPC: TIBStringField;
    TParcCRTIPOBLT: TIBStringField;
    TParcCRTEXTOBLT: TMemoField;
    TParcCREXPORTA: TSmallintField;
    TParcCRDIASATRASO: TIntegerField;
    TParcCRNUMORDEM: TSmallintField;
    TParcCPPARCIAL: TIBStringField;
    TParcCPNUMFISC: TIntegerField;
    WParPCOD_INTERNO: TIBStringField;
    WParPCOD_PARCELACP: TIntegerField;
    WParPCOD_CTAPAGAR: TIntegerField;
    WParPCOD_COTA: TIntegerField;
    WParPCOD_PARANT: TIntegerField;
    WParPCOBRANCA: TIBStringField;
    WParPDTVENC: TDateField;
    WParPNUMPARC: TIBStringField;
    WParPVALOR: TIBBCDField;
    WParPVALORPG: TIBBCDField;
    WParPDTDEBITO: TDateField;
    WParPFECH: TIBStringField;
    WParPCLASSIFICACAO: TIBStringField;
    WParPDESCRICAO: TIBStringField;
    WParPCOD_PLNCTA: TIntegerField;
    WParPCOD_FORMPAG: TIntegerField;
    WParPCOD_LOJA: TIntegerField;
    WParPFORMPAG: TIBStringField;
    WParPCOD_FORNEC: TIntegerField;
    WParPCOD_PESSOA: TIntegerField;
    WParPNOME: TIBStringField;
    WParPDTLANC: TDateField;
    WParPNUMDOC: TIBStringField;
    WParPHISTORICO: TIBStringField;
    WParPPREVISAO: TIBStringField;
    WParPDTREFER: TDateField;
    WParPMARK: TIBStringField;
    WParPNUMFISC: TIntegerField;
    TCtaRCOD_CTARECEBER: TIntegerField;
    TCtaRCOD_USUARIO: TIntegerField;
    TCtaRDTLANC: TDateField;
    TCtaRCOBRANCA: TIBStringField;
    TCtaRCOD_CLIENTE: TIntegerField;
    TCtaRCOD_PLNCTA: TIntegerField;
    TCtaRHISTORICO: TIBStringField;
    TCtaRTIPOGERADOR: TIBStringField;
    TCtaRCOD_GERADOR: TIntegerField;
    TCtaRVALOR: TIBBCDField;
    TCtaRCOD_COTAMOEDA: TIntegerField;
    TCtaRCOD_FORMPAG: TIntegerField;
    TCtaRNUMDOC: TIBStringField;
    TCtaRCOD_PLNCTASERV: TIntegerField;
    TCtaRNUMCARTAO2: TIBStringField;
    TCtaRCOD_VENDEDOR: TIntegerField;
    WCtaRCOD_CTARECEBER: TIntegerField;
    WCtaRCOD_FORMPAG: TIntegerField;
    WCtaRCOD_CLIENTE: TIntegerField;
    WCtaRCOD_PLNCTA: TIntegerField;
    WCtaRCOBRANCA: TIBStringField;
    WCtaRDTLANC: TDateField;
    WCtaRHISTORICO: TIBStringField;
    WCtaRNUMDOC: TIBStringField;
    WCtaRVALOR: TIBBCDField;
    WCtaRCOD_USUARIO: TIntegerField;
    WCtaRLOGIN: TIBStringField;
    WCtaRCOD_LOJA: TIntegerField;
    WCtaRNUMCARTAO: TIBStringField;
    WParRCOD_INTERNO: TIBStringField;
    WParRCOD_PARCELACR: TIntegerField;
    WParRCOD_CTARECEBER: TIntegerField;
    WParRCOD_COTA: TIntegerField;
    WParRCOD_PARANT: TIntegerField;
    WParRCOBRANCA: TIBStringField;
    WParRDTVENC: TDateField;
    WParRNUMPARC: TIBStringField;
    WParRVALOR: TIBBCDField;
    WParRVALORPG: TIBBCDField;
    WParRTIPOBOLETO: TIBStringField;
    WParRNUMCTA: TIBStringField;
    WParRDTDEBITO: TDateField;
    WParRFECH: TIBStringField;
    WParRCLASSIFICACAO: TIBStringField;
    WParRDESCRICAO: TIBStringField;
    WParRCOD_PLNCTA: TIntegerField;
    WParRCOD_FORMPAG: TIntegerField;
    WParRCOD_LOJA: TIntegerField;
    WParRFORMPAG: TIBStringField;
    WParRCOD_CLIENTE: TIntegerField;
    WParRCOD_PESSOA: TIntegerField;
    WParRNOME: TIBStringField;
    WParRDTLANC: TDateField;
    WParRNUMDOC: TIBStringField;
    WParRHISTORICO: TIBStringField;
    WParRMARK: TIBStringField;
    WParRNUMBOLETO: TIBStringField;
    WParRNUMFISC: TIntegerField;
    WParRREMESSA: TIBStringField;
    WParRCOD_CTACOR: TIntegerField;
    WParRSCPC: TIBStringField;
    WParRNUMCARTAO: TIBStringField;
    WParRDIASATRASO: TIntegerField;
    WParRVENDEDOR: TIBStringField;
    TParcCPESTRU: TIBStringField;
    TParcCRPARCIAL: TIBStringField;
    TParcCRESTRU: TIBStringField;
    TPlnCtaCONTAPADRAO: TIBStringField;
    TPlnCtaMOSTRANORMAL: TIBStringField;
    TPlnCtaCOD_ESTOQUE: TIntegerField;
    TParcCPNUMBOLETO: TIBStringField;
    WParPNUMBOLETO: TIBStringField;
    TParcCPVALEXT: TIBStringField;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

  Procedure SelectPlnCtaEmpresa; //Seleciona as contas do plano de acordo com empresa informada no painel de acesso no menu

var
  DMCONTA: TDMCONTA;

implementation

uses UMenu, Alxor32, UCtaReceber;

{$R *.DFM}

Procedure SelectPlnCtaEmpresa; //Seleciona as contas do plano de acordo com empresa informada no painel de acesso no menu
Begin
	//prepara e executa sql
   DMCONTA.TPlnCta.Close;
   DMCONTA.TPlnCta.SQL.Clear;
   DMCONTA.TPlnCta.SQL.Add('select * ');
   DMCONTA.TPlnCta.SQL.Add(' from PLNCTA WHERE COD_FILIAL=:CODEMPRESA ');
   DMCONTA.TPlnCta.SQL.Add('Order By PLNCTA.CLASSIFICACAO');
   DMCONTA.TPlnCta.ParamByName('CODEMPRESA').AsString:=FMenu.LCODEMPRESA.Caption;
   DMCONTA.TPlnCta.Open;
End;

end.
